# Generated by Django 2.1.5 on 2019-02-13 05:44

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('start_date', models.DateField(default=datetime.date(2019, 2, 13))),
                ('end_date', models.DateField(default=datetime.date(2019, 2, 13))),
                ('amount_per_month', models.IntegerField(default=0)),
                ('amount_per_day', models.IntegerField(default=0)),
                ('start_date_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('end_date_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('rev1_status', models.IntegerField(default=0)),
                ('rev2_status', models.IntegerField(default=0)),
                ('rev3_status', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
