# Generated by Django 2.1.5 on 2019-02-11 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2019, 2, 11, 18, 42, 50, 616860, tzinfo=utc))),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('amount_per_month', models.IntegerField(default=0)),
                ('amount_per_day', models.IntegerField(default=0)),
                ('start_date_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('end_date_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
