<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-02-12 12:57
=======
# Generated by Django 2.1.5 on 2019-02-12 12:43
>>>>>>> 428e05ae3007acfed02d9bfe4f970b0669c7e784

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('start_date', models.DateField(default=datetime.date(2019, 2, 12))),
                ('end_date', models.DateField(default=datetime.date(2019, 2, 12))),
                ('amount_per_month', models.IntegerField(default=0)),
                ('amount_per_day', models.IntegerField(default=0)),
                ('start_date_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('end_date_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('rev1_status', models.IntegerField(default=0)),
                ('rev2_status', models.IntegerField(default=0)),
                ('rev3_status', models.IntegerField(default=0)),
            ],
        ),
    ]
