# Generated by Django 2.1.5 on 2019-02-11 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 11, 19, 11, 4, 775782, tzinfo=utc)),
        ),
    ]
