# Generated by Django 2.1.5 on 2019-02-12 05:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190211_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 12, 5, 17, 47, 752016, tzinfo=utc)),
        ),
    ]
