# Generated by Django 2.1.5 on 2019-02-13 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 2, 13)),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 2, 13)),
        ),
    ]
