# Generated by Django 2.1.5 on 2019-02-12 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190212_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 2, 12)),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 2, 12)),
        ),
    ]
