# Generated by Django 2.1.5 on 2019-02-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190212_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rev1_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rev2_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rev3_status',
            field=models.IntegerField(default=0),
        ),
    ]
